# Generated by Django 5.1.1 on 2024-10-17 07:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_ingredient_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(
                null=True,
                upload_to=core.models.recipe_image_file_path),
        ),
    ]
